---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sxapi-operator
  namespace: openshift-operators
spec:
  channel: fast
  installPlanApproval: Automatic
  name: sxapi-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: sxapi-operator.v0.1.0