---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: sxapi-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/startx/sxapi-operator-catalog:v0.0.12
  displayName: SXApi Operator
  publisher: startx.fr
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sxapi-operator
  namespace: openshift-operators
spec:
  channel: alpha
  name: sxapi-operator
  source: sxapi-catalog
  sourceNamespace: openshift-marketplace
