---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: sxapi-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/startx/sxapi-operator-catalog:v0.0.9
  displayName: SXApi Operator
  publisher: startx.fr
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: sxapi-group
  namespace: openshift-marketplace
spec:
  targetNamespaces:
  - default
  - demo-sxapi
  - sxapi
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sxapi-operator
  namespace: default
spec:
  channel: alpha
  name: sxapi-operator
  source: sxapi-catalog
  sourceNamespace: openshift-marketplace
