#!/bin/bash
PROJECT_PATH=`dirname $(readlink -f $0)`

# menu for usage command
function menuUsage {
cat <<EOF

This client helps you manage the lifecycle of the sxapi operator.

Usage:
  ./sx-operator <action> [flags]

- Actions  :
  - commit                   commit a change to the current branch
  - build operator           Build the sxapi operator
  - build bundle             Build the sxapi operator bundle
  - build all                Build all the sxapi operator components (operator, bundle and OLM catalog)
  - test scorecard           Build the sxapi operator and scorecard it
  - test bundle              Build the sxapi operator bundle and deploy it
  - test in-cluster          Deploy the catalog, operatorgroup and subscription into the cluster
  - test bundle-upgrade      Build the sxapi operator bundle and upgrade the deployed one
  - test all                 Build all the sxapi operator components (operator, bundle and OLM catalog)
  - publish operator         Build and publish the sxapi operator
  - publish bundle           Build and publish the sxapi operator bundle
  - publish catalog          Build and publish the sxapi operator catalog
  - publish all              Build and publish all the sxapi operator components (operator, bundle and OLM catalog)
  - deploy                   Deploy the OLM catalog and a subscription (with operatorGroup) to test the operator availability

- Examples  :
  ./sx-operator commit      Commit a change to the current branch
  ./sx-operator build all   Build all the sxapi operator components (operator, bundle and OLM catalog)
  ./sx-operator publish all Build and publish all the sxapi operator components (operator, bundle and OLM catalog)
  ./sx-operator deploy      Deploy the OLM catalog and a subscription (with operatorGroup) to test the operator availability

EOF
}



if [[ "$1" != "" ]]; then
    case $1 in
        commit)
            git add $PROJECT_PATH
            git commit
        ;;
        deploy)
            oc apply -f load-catalog.yaml
        ;;
        build)
            case $2 in
                operator)
                    make docker-build
                    git add $PROJECT_PATH
                    git commit $PROJECT_PATH
                ;;
                bundle)
                    make bundle bundle-build
                    git add $PROJECT_PATH
                    git commit $PROJECT_PATH
                ;;
                catalog)
                    make catalog-build
                    git add $PROJECT_PATH
                    git commit $PROJECT_PATH
                ;;
                all)
                    make docker-build bundle bundle-build catalog-build
                    git add $PROJECT_PATH
                    git commit $PROJECT_PATH
                ;;
                *)
                    menuUsage
                ;;
            esac
        ;;
        test)
            case $2 in
                scorecard)
                    make docker-build docker-push bundle bundle-build
                    operator-sdk scorecard ./bundle
                ;;
                bundle)
                    make docker-build docker-push bundle bundle-build bundle-push
                    operator-sdk run bundle ./bundle
                ;;
                bundle-upgrade)
                    make docker-build docker-push bundle bundle-build bundle-push
                    operator-sdk run bundle-upgrade ./bundle
                ;;
                in-cluster)
                    oc apply -f ./load-catalog.yaml
                ;;
                all)
                    make docker-build docker-push bundle bundle-build bundle-push
                    oc apply -f ./load-catalog.yaml
                    operator-sdk run bundle quay.io/startx/sxapi-operator-bundle:v0.1.0
                ;;
                *)
                    menuUsage
                ;;
            esac
        ;;
        publish)
            case $2 in
                operator)
                    make docker-build docker-push
                    git add $PROJECT_PATH
                    git commit $PROJECT_PATH
                ;;
                bundle)
                    make bundle bundle-build bundle-push
                    git add $PROJECT_PATH
                    git commit $PROJECT_PATH
                ;;
                catalog)
                    make catalog-build catalog-push
                    git add $PROJECT_PATH
                    git commit $PROJECT_PATH
                ;;
                all)
                    make docker-build docker-push bundle bundle-build bundle-push catalog-build catalog-push
                    git add $PROJECT_PATH
                    git commit $PROJECT_PATH
                ;;
                *)
                    menuUsage
                ;;
            esac
        ;;
        *)  menuUsage;;
    esac
else
    menuUsage
fi
