# permissions for end users to view sxapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sxapi-viewer-role
rules:
- apiGroups:
  - sxapi.startx.fr
  resources:
  - sxapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sxapi.startx.fr
  resources:
  - sxapis/status
  verbs:
  - get
