apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "sxapi.startx.fr/v1alpha1",
          "kind": "SXApi",
          "metadata": {
            "name": "sxapi-example-prod"
          },
          "spec": {
            "context": {
              "cluster": "localhost",
              "scope": "bu-marketing",
              "environment": "prod",
              "app": "example",
              "component": "sxapi",
              "version": "0.0.1"
            },
            "sxapi": {
              "data": "sxapi.yml: |-\n  name: default\n  description: Description of the default sxapi instance (defined in sxapi operator)\n  version: \"0.3.57\"\n  debug: false\n  resources:\n    serviceinfo-sample:\n      _class: serviceinfo\n  log:\n    filters:\n      level: '0,1,2'\n      type: info,error,warn\n  server:\n    port: '8077'\n    endpoints:\n    - path: \"/\"\n      body: |-\n          <html>\n          <head><title>Example application production</title></head>\n          <body>\n            <h1>SXAPI is live in production (operator's managed)</h1>\n            <p>\n              This example is deployed using the sxapi operator example based on the \n              <a href=\"https://helm-repository.readthedocs.io/en/latest/charts/sxapi.html\" target=\"_blank\">sxapi chart</a>\n              available in the <a href=\"https://helm-repository.readthedocs.io\" target=\"_blank\">startx helm repository</a>. \n            </p>\n            <p>\n              You could check the following endpoints :</p>\n            <ul>\n              <li><a href=\"./health\">Health status (used by readiness probe)</a></li>\n              <li><a href=\"./info\">Information about the application</a></li>\n            </ul>\n          </body>\n          </html>\n    - path: \"/health\"\n      resource: serviceinfo-sample\n      endpoint: health\n    - path: \"/info\"\n      resource: serviceinfo-sample\n      endpoint: info\n",
              "debug": false,
              "expose": {
                "enabled": true
              },
              "profile": "prod:start",
              "replicas": 2
            }
          }
        },
        {
          "apiVersion": "sxapi.startx.fr/v1alpha1",
          "kind": "SXApi",
          "metadata": {
            "name": "sxapi-example-dev"
          },
          "spec": {
            "context": {
              "cluster": "localhost",
              "scope": "bu-marketing",
              "environment": "dev",
              "app": "example",
              "component": "sxapi",
              "version": "0.0.2"
            },
            "sxapi": {
              "data": "sxapi.yml: |-\n  name: default\n  description: Description of the default sxapi instance (defined in sxapi operator)\n  version: \"0.3.57\"\n  debug: true\n  resources:\n    serviceinfo-sample:\n      _class: serviceinfo\n  log:\n    filters:\n      level: '0,1,2,3,4'\n      type: debug,info,error,warn\n  server:\n    port: '8077'\n    endpoints:\n    - path: \"/\"\n      body: |-\n          <html>\n          <head><title>Example application developement</title></head>\n          <body>\n            <h1>SXAPI is live in developement (operator's managed)</h1>\n            <p>\n              This example is deployed using the sxapi operator example based on the \n              <a href=\"https://helm-repository.readthedocs.io/en/latest/charts/sxapi.html\" target=\"_blank\">sxapi chart</a>\n              available in the <a href=\"https://helm-repository.readthedocs.io\" target=\"_blank\">startx helm repository</a>. \n            </p>\n            <p>\n              You could check the following endpoints :</p>\n            <ul>\n              <li><a href=\"./health\">Health status (used by readiness probe)</a></li>\n              <li><a href=\"./info\">Information about the application</a></li>\n            </ul>\n          </body>\n          </html>\n    - path: \"/health\"\n      resource: serviceinfo-sample\n      endpoint: health\n    - path: \"/info\"\n      resource: serviceinfo-sample\n      endpoint: info\n",
              "debug": true,
              "expose": {
                "enabled": false
              },
              "profile": "prod:start",
              "replicas": 1
            }
          }
        }
      ]
    capabilities: Seamless Upgrades
    categories: Application Runtime, Developer Tools, Integration & Delivery
    certified: "false"
    containerImage: quay.io/startx/sxapi-operator:v0.0.12
    description: Run codeless micro-applications on Kubernetes / Openshift clusters
      using the SXApi engine. For more information see https://sxapi-core.readthedocs.io
    olm.operatorGroup: global-operators
    olm.operatorNamespace: openshift-operators
    olm.targetNamespaces: openshift-operators
    operatorframework.io/suggested-namespace: openshift-operators
    operators.openshift.io/valid-subscription: '["OpenShift Container Platform"]'
    operators.operatorframework.io/builder: operator-sdk-v1.8.0+git
    operators.operatorframework.io/project_layout: helm.sdk.operatorframework.io/v1
    repository: https://github.com/startx/sxapi-operator
    support: STARTX
  name: sxapi-operator.v0.0.12
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Deployement of an SXApi application
      displayName: SXApi
      kind: SXApi
      name: sxapis.sxapi.startx.fr
      resources:
      - kind: ConfigMap
        name: ""
        version: v1
      - kind: Secret
        name: ""
        version: v1
      - kind: Deployment
        name: ""
        version: v1
      - kind: ReplicaSet
        name: ""
        version: v1
      - kind: Pod
        name: ""
        version: v1
      - kind: Service
        name: ""
        version: v1
      - kind: Route
        name: ""
        version: v1
      - kind: Prometheus
        name: ""
        version: v1
      - kind: ServiceMonitor
        name: ""
        version: v1
      - kind: StatefulSet
        name: ""
        version: v1
      specDescriptors:
      - description: The context of the deployment
        displayName: Context
        path: context
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:Context
      - description: The name of the cluster
        displayName: Cluster name
        path: context.cluster
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:Context
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: The name of the component
        displayName: Component name
        path: context.component
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:Context
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: The name of the environment
        displayName: Environment name
        path: context.environment
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:Context
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: The name of the scope
        displayName: Scope name
        path: context.scope
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:Context
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: The name of the application
        displayName: Application name
        path: context.app
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:Context
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: The version of the application
        displayName: Application version
        path: context.version
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:Context
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: Configuration of the application
        displayName: SXapi
        path: sxapi
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:SXApi
      - description: Replicas number for this deployment
        displayName: Replicas
        path: sxapi.replicas
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:SXApi
        - urn:alm:descriptor:com.tectonic.ui:podCount
      - description: Expose the application
        displayName: Expose application
        path: sxapi.expose.enabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:fieldGroup:SXApi
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: Enable debug mode behaviours
        displayName: Debug
        path: sxapi.debug
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      statusDescriptors:
      - description: The status of the sxapi application.
        displayName: State
        path: conditions.0.status
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      - description: The name of the sxapi application.
        displayName: Name
        path: deployedRelease.name
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:text
      version: v1alpha1
  description: "## Overview\n\nThe SXApi Operator manages the full lifecycle of [sxapi](https://sxapi-core.readthedocs.io)\napplications.
    \ The operator's goal is to automate the tasks required when deploying\nan sxapi
    application.\n\nBeyond installation, the operator helps to automate the\nprocess
    of upgrading, backing up and restoring as needed and remove the human\nas much
    as possible. \n\nThe operator aims to provide the following, and is a work in
    progress.\n\n* Easy configuration and installation of the SXApi resources with
    sane defaults to get up and running quickly. \n* Autoscale the SXApi computes
    resources as necessary to handle workload (tech preview).\n\n## Usage\n\nDeploy
    a basic SXApi application by creating a new SXApi resource in your current namespace.\n\n```yaml\napiVersion:
    sxapi.startx.fr/v1alpha1\nkind: SXApi\nmetadata:\n  name: example-sxapi\nspec:
    \n  context:\n    app: example-sxapi\n    component: sxapi\n    environment: demo\n
    \   scope: example\n    version: 0.0.1\n  sxapi:\n    data: |\n      sxapi.yml:
    |-\n        name: example\n        description: Description of the example sxapi
    instance (defined in sxapi operator)\n        version: \\\"0.3.57\\\"\n        debug:
    false\n        resources: \n          serviceinfo-sample:\n            _class:
    serviceinfo\n        log:\n          filters:\n            level: '0,1,2,3,4'\n
    \           type: debug,info,error,warn\n        server:\n          port: '8077'\n
    \         endpoints:\n          - path: \\\"/\\\"\n            body: |-\n                <html>\n
    \               <head><title>Example application (operator default values)</title></head>\n
    \               <body>\n                  <h1>SXAPI is live ! (operator's managed)</h1>\n
    \                 <p>\n                    This example is deployed using the
    sxapi operator example\n                    based on the <a href=\\\"https://helm-repository.readthedocs.io/en/latest/charts/sxapi.html\\\"
    target=\\\"_blank\\\">sxapi chart</a>\n                    available in the <a
    href=\\\"https://helm-repository.readthedocs.io\\\" target=\\\"_blank\\\">startx
    helm repository</a>. \n                  </p>\n                  <p>\n                    You
    could check the following endpoints :\n                  </p>\n                  <ul>\n
    \                   <li><a href=\\\"./health\\\">Health status (used by readiness
    probe)</a></li>\n                    <li><a href=\\\"./info\\\">Information about
    the application</a></li>\n                  </ul>\n                </body>\n                </html>\n
    \         - path: \\\"/health\\\"\n            resource: serviceinfo-sample\n
    \           endpoint: health\n          - path: \\\"/info\\\"\n            resource:
    serviceinfo-sample\n            endpoint: info\n```\nSee the [documentation](https://sxapi-core.readthedocs.io)\nand
    examples on [github](https://github.com/startxfr/sxapi-core) for more information."
  displayName: SXApi micro-framework operator
  icon:
  - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iNjUiIGhlaWdodD0iNjUiIHZlcnNpb249IjEuMSIgdmlld0JveD0iMCAwIDY1IDY1IiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgogPHRpdGxlPlNYQVBJIGxvZ288L3RpdGxlPgogPGcgdHJhbnNmb3JtPSJtYXRyaXgoMi45MjEgMCAwIDIuOTIxIC0zMy44ODQgLTc1My45NykiPgogIDxnIGlkPSJhIiB0cmFuc2Zvcm09Im1hdHJpeCguMjgxNCAwIDAgLjI4MTQgOC41ODE4IDIyOC41NykiIGZpbGw9Im5vbmUiPgogICA8cGF0aCBpZD0iYiIgZD0ibTI4LjU5MSAxNzMuODcgMjUuMzY3LTI1LjM3NS0wLjAxOTAxLTE1LjQwMiIgc3Ryb2tlPSIjZmYwZTJmIiBzdHJva2Utd2lkdGg9IjQuOTQ1OCIvPgogICA8ZyBpZD0iYyIgdHJhbnNmb3JtPSJtYXRyaXgoLjM1MzI3IDAgMCAuMzUzMjcgMTAuMzk3IDY5LjUyOSkiIHN0cm9rZT0iIzRkOWVmZiIgc3Ryb2tlLXdpZHRoPSIxNCI+CiAgICA8cGF0aCBkPSJtMTYuODczIDI2Mi4xMiA1My4xODEtNTIuNzY0LTAuMDAyOC00NS40NjQtMTIuMDU1LTExLjc0MSIvPgogICAgPGNpcmNsZSBjeD0iNTAuODUzIiBjeT0iMTQ0LjIzIiByPSIxMi4xMDkiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIvPgogICA8L2c+CiAgIDxnIGlkPSJkIiBzdHJva2U9IiM4YzAyMTUiPgogICAgPHBhdGggZD0ibTM0LjMzOCAxODAuMTEgMjAuOTc0LTIwLjE2MmgxMy4xOTkiIHN0cm9rZS13aWR0aD0iNC45NDU4Ii8+CiAgICA8cmVjdCB4PSI2OC45OTEiIHk9IjE1NC44NiIgd2lkdGg9IjEwLjQ2NyIgaGVpZ2h0PSIxMC40NjciIHJ4PSIwIiByeT0iMCIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2Utd2lkdGg9IjQuMjM5MiIvPgogICA8L2c+CiAgIDxnIGlkPSJlIiB0cmFuc2Zvcm09Im1hdHJpeCguMzUzMjcgMCAwIC4zNTMyNyAxMC4zOTcgNjkuNTI5KSIgc3Ryb2tlPSIjMmYxZGZmIj4KICAgIDxwYXRoIGQ9Im0xMjEuMTQgMTM0LjMxLTI4Ljg1NCAyOS4yNTUtMC4wMDkxMDYgNTYuMzc4LTU4LjQzNyA1OS4xNDQiIHN0cm9rZS13aWR0aD0iMTQiLz4KICAgIDxwYXRoIGQ9Im0xMzAuMTcgMTUwLjEzLTI1LjkzOC0yNS45MzggMzUuNDMyLTkuNDkzOXoiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLXdpZHRoPSIxMiIvPgogICA8L2c+CiAgPC9nPgogPC9nPgo8L3N2Zz4K
    mediatype: image/svg+xml
  install:
    spec:
      deployments: []
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - startx
  - sxapi
  - micro-service
  - faas
  - codeless
  - nodejs
  - api
  - kubernetes
  - open source
  labels:
    alm-owner-sxpi: sxapi-operator
    operated-by: sxapi-operator
  links:
  - name: SXApi Documentation
    url: https://sxapi-core.readthedocs.io
  - name: SXApi Operator Documentation
    url: https://sxapi-core.readthedocs.io#operator
  - name: SXApi Source Code
    url: https://github.com/startxfr/sxapi-core
  - name: SXApi Operator Source Code
    url: https://github.com/startxfr/sxapi-operator
  maintainers:
  - email: dev@startx.fr
    name: startx
  maturity: alpha
  minKubeVersion: 1.20.0
  provider:
    name: STARTX
    url: https://sxapi-core.readthedocs.io
  replaces: sxapi-operator.v0.0.11
  selector:
    matchLabels:
      alm-owner-sxpi: sxapi-operator
      operated-by: sxapi-operator
  version: 0.0.12
