apiVersion: sxapi.startx.fr/v1alpha1
kind: SXApi
metadata:
  name: sxapi-sample
spec:
  context:
    app: default-sxapi
    cluster: localhost
    component: sxapi
    environment: myenv
    scope: myscope
    version: 0.0.1
  sxapi:
    data: |
      sxapi.yml: |-
        name: {{ include "startx.appName" . }}
        description: Description of {{ include "startx.appName" . }}
        version: {{ include "startx.appVersion" . }}
        debug: "{{- .Values.sxapi.debug }}"
        resources:
          serviceinfo-sample:
            _class: serviceinfo
        log:
          filters:
            level: '0,1,2,3,4'
            type: debug,info,error,warn
        server:
          port: '8077'
          endpoints:
          - path: "/"
            desc: Display welcome message (HTML)
            body: |-
                <html>
                <head><title>Example application {{ include "startx.appName" . }}</title></head>
                <body><h1>API {{ include "startx.appName" . }} is live !</h1></body>
                </html>
          - path: "/health"
            resource: serviceinfo-sample
            endpoint: health
          - path: "/info"
            resource: serviceinfo-sample
            endpoint: info
          - path: "/ping"
            desc: Ping the application. Return a sample message in json
            code: '200'
            body: pong
    debug: true
    expose:
      enabled: true
      kind: route
    profile: prod:start
    replicas: 2
    service:
      enabled: true
    version: 0.3.57
  
  
