apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "startx.appName" . }}
  labels:
    app.kubernetes.io/name: "{{- include "startx.appName" . -}}-{{- include "startx.appVersion" . -}}-deployment"
    {{- include "sxapi.labels" . | nindent 4 }}
  annotations:
    {{- include "sxapi.annotations" . | nindent 4 }}
    checksum/config: {{ include (print $.Template.BasePath "/cm-lib.yaml") . | sha256sum }}
    argocd.argoproj.io/sync-wave: "30"
spec:
  replicas: {{ .Values.sxapi.replicas  }}
  selector:
    matchLabels:
      app: {{ include "startx.appName" . }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ include "startx.appName" . }}-{{ include "startx.appVersion" . }}-pod"
        {{- include "sxapi.labels" . | nindent 8 }}
        app: {{ include "startx.appName" . }}
      annotations:
        {{- include "sxapi.annotations" . | nindent 8 }}
    spec: 
      containers:
        - name: sxapi
          image: "startx/sxapi:{{- .Values.sxapi.version }}"
          env:
            - name: SX_DEBUG
              value: "{{- .Values.sxapi.debug }}"
            - name: SX_VERBOSE
              value: "true"
          envFrom:
            - configMapRef:
                name: {{ include "startx.appName" . }}-app
          command: [ "npm" , "run", "{{- .Values.sxapi.profile }}" ]
          ports:
          - containerPort: 8077
            name: http
            protocol: TCP
          livenessProbe:
            initialDelaySeconds: 5
            tcpSocket:
              port: 8077
            timeoutSeconds: 2
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            initialDelaySeconds: 7
            tcpSocket:
              port: 8077
            timeoutSeconds: 2
            periodSeconds: 6
            successThreshold: 1
            failureThreshold: 3
          # resources:
          #   limits:
          #     cpu: 200m
          #     memory: 64Mi
          #   requests:
          #     cpu: 50m
          #     memory: 32Mi
          terminationMessagePath: "/dev/termination-log"
          imagePullPolicy: Always
          volumeMounts:
            - name: "sxapi-deploy-log"
              mountPath: "/var/log/httpd"
            - name: sxapi-deploy-conf
              mountPath: "/conf"
      volumes:
        - name: "sxapi-deploy-log"
          emptyDir:
            medium: ""
        - name: sxapi-deploy-conf
          configMap:
            name: "{{ include "startx.appName" . }}-lib"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
