{{- if .Values.sxapi.service -}}{{- if .Values.sxapi.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "startx.appName" . }}
  labels:
    app.kubernetes.io/name: "{{- include "startx.appName" . -}}-{{- include "startx.appVersion" . -}}-service"
    {{- include "sxapi.labels" . | nindent 4 }}
    app: {{ include "startx.appName" . }}
  annotations:
    {{- include "sxapi.annotations" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8077
  selector:
    app: {{ include "startx.appName" . }}
  type: ClusterIP
  sessionAffinity: None
{{- end -}}{{- end -}}
